- README.md
- examples/clic.md
This adds text on how to run simulation and reconstruction for CLIC, at the moment the k4run instructions still require the manual modification of the steering file. What would be the best way to add command line arguments for this?
> Example: add example running sim and reco for CLIC

- examples/clic.md
* `$LCGEO` points to to share/compact.
* syntax error with too many `"`
> ClicExample: fix sed replacing for detmodel

- spack-build-instructions/README.md
- spack-build-instructions/spack-advanced.md
- spack-build-instructions/spack-developer-workflows.md
Add some documentation on how to use `spack dev-build` and the development capabilities of spack environments for developer workflows. These capabilities of spack are not yet really documented, but can be quite useful.
> Add documentation for spack developer workflows

- examples/clic.md
Each of the bash codecells runs in a new shell when executing as a notebook, so the directory changes need to be repeated in each cell. Not sure if there is a more elegant way, but since this can be used for both automatic checks and  to create notebooks to be run on SWAN I think this is worth it.
- fix paths in examples/clic.md to make it run as notebook
> [clicexample] update paths

- examples/clic.md
- Update CLIC documentation for removal of END_TAG in k4MarlinWrapper
> update docs for removal of END_TAG

- README.md
- conf.py
- setup-and-getting-started/README.md
- spack-build-instructions/README.md
- spack-build-instructions/spack-buildcache.md
- spack-build-instructions/spack-developer-workflows.md
- Replace all appearances of "Key4HEP" with "Key4hep". Leave only the talk titles of past presentations untouched.
> Update docs to use agreed upon naming scheme

- .github/scripts/fetch_external_sources.sh
- .github/workflows/build.yml
- .github/workflows/publish.yml
- CONTRIBUTING.md
- conf.py
- developing-key4hep-software/Key4hepCMakeGuide.md
- developing-key4hep-software/Key4hepSoftwareGit.md
- developing-key4hep-software/SpackForDevelopers.md
- requirements.txt
- Add a build workflow that builds the documentation and checks that all links are valid
- Fix a few broken links
- Automatically try to fetch markdown files referenced in the toplevel toc (README.md) file from external github repositories
- Switch from `recommonmark` to `myst_parser` for parsing markdown file, since the former has been deprecated: readthedocs/recommonmark#221
Fixes #29 
Makes #13 samewhat easier to do as adding an external file should be enough to pull it in
The fetching of additional files from external github repositories works by first checking if the file exists in the checked out repository. If that is not the case, then it will look in the `key4hep`, `HEP-FCC`, `AIDASoft` and `iLCSoft` github organisations for the file (in this …
> Add build workflow, make it check for deadlinks and add auto fetching of external docs

- .github/scripts/fetch_external_sources.sh
- .gitignore
- README.md
- Add a bit of documentation for k4SimDelphes (standalone running only at the moment)
- Make the fetch script also work with `main` as default branch
> Add k4simdelphes documentation

- README.md
- Adds documentation files on EDM converters and How to do multithreading with Gaudi
Needs https://github.com/key4hep/k4MarlinWrapper/pull/84
> link to k4marlinwrapper extra doc files

- developing-key4hep-software/SpackForDevelopers.md
- Link from the developer to the librarian instructions as a tip on how to obtain spack
> Add spack tip to developer instructions

- .github/scripts/fetch_external_sources.sh
- README.md
- tutorials/README.md
- tutorials/example.md
- Add a tutorial section to the page.
- Move existing starterkit documentation into the tutorials section
@jmcarcell @andresailer @gaede as discussed I added a tutorial section to the page. Currently there is an empty "example" tutorial just to demonstrate the layout in the end.
This looks like this in the current page:
I will start to add the converter tutorial to this in a separate PR. I think we could potentially merge this first (or at least everyone can start from here). For adding a new tutorial you simply need to add the markdown or rst file into the `eval_rst` block in the `README.md`.
> Add a tutorial section to the page

- developing-key4hep-software/README.md
- developing-key4hep-software/SinglePackage.md
- developing-key4hep-software/SpackForDevelopers.md
- Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines
- ...
This PR will add some documentation on developing
> Add instructions and documentation on developing

- developing-key4hep-software/WritingAlgorithms.md
- Add documentation about the functional algorithms in Gaudi
> Add documentation about the functional algorithms

- tutorials/README.md
- Fix the path to the new converter documentation in k4MarlinWrapper, needed after https://github.com/key4hep/k4MarlinWrapper/pull/149
> Fix the path to the new converter documentation

- .github/scripts/fetch_external_sources.sh
- .gitignore
- README.md
- how-tos/README.md
- tutorials/README.md
- tutorials/example.md
- Add a *How-To and Instructions* section and populate it with existing content
- EDM4hep intro from `key4hep-tutorials`
- Podio In-/Output from k4FWCore
- Add the tutorial for running sim / reco with ILD 
> Add a how-to / instructions section and populate it with existing content

- how-tos/README.md
- Add the existing LCIO to EDM4hep conversion documentation to how-to section.
> Add LCIO to EDM4hep conversion to how-to section

- tutorials/README.md
- Make link to key4hep-tutorials repo more apparent
> Make link to key4hep-tutorials repo more apparent

- conf.py
- requirements.txt
- Remove the dependency from `starterkit-ci` since we don't really use much of it.
> Remove the starterkit-ci dependency

- .github/workflows/build.yml
- .github/workflows/publish.yml
- Update github actions to their latest versions to fix warnings when running them
- Bump the python version to 3.11
> Update github actions to latest version and bump python version

- conf.py
- developing-key4hep-software/WritingAlgorithms.md
- Ignore links to the CERN TWiki in the link check as they might require login
> Ignore TWiki that requires login from linkcheck

- .github/workflows/build.yml
- Add `workflow_dispatch` to the triggers for the `build` workflow to make it manually triggerable
> Make the build workflow manually triggerable

- spack-build-instructions-for-librarians/spack-advanced.md
- Fix link to spack documentation that has gone out of sync due to https://github.com/spack/spack-tutorial/pull/355
> Fix link to spack documentation

- setup-and-getting-started/README.md
- Update the information about the supported OSs
> Update information about supported OSs

- .github/workflows/build.yml
- .github/workflows/publish.yml
- conf.py
- Don't check opensource.org via linkcheck when running in github actions since cloudflare is apparently detecting that and blocking us from doing so
- Switch to python 3.12 for running the documentation building
> Don't check opensource.org links in github actions

- .github/scripts/fetch_external_sources.sh
- README.md
- Added `--force` option to the source fetching script that allows to  re-download sources even if they are already present
Updating the sources for local development was a little cumbersome as it required manually finding and deleting files in order to download updated version.
> Add `--force` option to fetch sources even if they are already present

- docs/getting_started/help.md
- Removed email address from help page
As discussed the email address is not very helpful as it's related to an e-group and sending to it is restricted to the members
> remove email from help page

- docs/developing-key4hep-software/WritingAlgorithms.md
- Replace legacy `k4DataSvc` with `IOSvc` in docs about writing algortihms
This replaces the last mentions of legacy `k4DataSvc` with recommended `IOSvc` as a part of  key4hep/k4FWCore#292
Some time later I'd like to refresh the whole page about writing algorithms to feature our flavour of functional algorithms.
> Use IOSvc in writing algs docs

- .github/workflows/build.yml
- .github/workflows/publish.yml
- README.md
- docs/conf.py
- index.html
Split building and deploying into two entirely separate steps. Make building a reusable (local) action in preparation for also having PR previews.
- Rework how pages are built and deployed in preparation of PR previews.
> Rework how documentation is published
